export const UPLOAD = 'UPLOAD'
export const DOWNLOAD = 'DOWNLOAD'
export const LIST = 'LIST'
export const SET_NEXT = 'SET_NEXT'
export const SET_BACK = 'SET_BACK'
export const GOTO_NEXT = 'GOTO_NEXT'
