module.exports = {
  person: 'person',
  product: 'product',
  clinic: 'clinic',
  lysate: 'lysate',
  blood: 'blood',
  doctor: 'doctor',
  patient: 'patient',
  prescription: 'prescription',
  production: 'production',
  filesystem: 'filesystem',
  document: 'document',
  user: 'user',
  role: 'role',
}
