module.exports = {
  person: 'person',
  user: 'user',
  product: 'product',
  parameter: 'parameter',
  location: 'location',
  clinic: 'clinic',
  lysate: 'lysate',
  source: 'source',
  doctor: 'doctor',
  patient: 'patient',
  prescription: 'prescription',
  production: 'production',
  dose: 'dose',
  science: 'science',
  data: 'data',
  filesystem: 'filesystem',
  document: 'document',
  role: 'role',
  permission: 'permission',
  member: 'member',
  right: 'right',
}
